package com.addiPlot.gnuplot;

public enum PLOT_STYLE
{
	LINES(0 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue()),
	POINTSTYLE(1 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue()),
	IMPULSES(2 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue()),
	LINESPOINTS(3 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue())),
	DOTS(4 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + 0),
	XERRORBARS(5 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR.getValue())),
	YERRORBARS(6 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR.getValue())),
	XYERRORBARS(7 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR.getValue())),
	BOXXYERROR(8 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL.getValue())),
	BOXES(9 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL.getValue())),
	BOXERROR(10 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL.getValue())),
	STEPS(11 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue()),
	FSTEPS(12 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue()),
	HISTEPS(13 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue()),
	VECTOR(14 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue()),
	CANDLESTICKS(15 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL.getValue())),
	FINANCEBARS(16 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue()),
	XERRORLINES(17 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR.getValue())),
	YERRORLINES(18 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR.getValue())),
	XYERRORLINES(19 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT.getValue() | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR.getValue())),
	FILLEDCURVES(21 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL.getValue()),
	PM3DSURFACE(22 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + 0),
	LABELPOINTS(23 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + 0),
	HISTOGRAMS(24 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL.getValue()),
	IMAGE(25 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + 0),
	RGBIMAGE(26 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + 0),
	RGBA_IMAGE(27 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + 0),
	CIRCLES(28 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE.getValue() + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL.getValue());

	private int intValue;
	private static java.util.HashMap<Integer, PLOT_STYLE> mappings;
	private static java.util.HashMap<Integer, PLOT_STYLE> getMappings()
	{
		if (mappings == null)
		{
			synchronized (PLOT_STYLE.class)
			{
				if (mappings == null)
				{
					mappings = new java.util.HashMap<Integer, PLOT_STYLE>();
				}
			}
		}
		return mappings;
	}

	private PLOT_STYLE(int value)
	{
		intValue = value;
		PLOT_STYLE.getMappings().put(value, this);
	}

	public int getValue()
	{
		return intValue;
	}

	public static PLOT_STYLE forValue(int value)
	{
		return getMappings().get(value);
	}
}