package com.addiPlot.gnuplot;

public enum PLOT_STYLE
{
	LINES(0 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE),
	POINTSTYLE(1 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT),
	IMPULSES(2 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE),
	LINESPOINTS(3 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE)),
	DOTS(4 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + 0),
	XERRORBARS(5 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR)),
	YERRORBARS(6 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR)),
	XYERRORBARS(7 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR)),
	BOXXYERROR(8 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL)),
	BOXES(9 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL)),
	BOXERROR(10 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL)),
	STEPS(11 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE),
	FSTEPS(12 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE),
	HISTEPS(13 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE),
	VECTOR(14 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE),
	CANDLESTICKS(15 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL)),
	FINANCEBARS(16 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE),
	XERRORLINES(17 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR)),
	YERRORLINES(18 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR)),
	XYERRORLINES(19 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + (e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_POINT | e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_ERRORBAR)),
	FILLEDCURVES(21 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL),
	PM3DSURFACE(22 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + 0),
	LABELPOINTS(23 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + 0),
	HISTOGRAMS(24 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL),
	IMAGE(25 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + 0),
	RGBIMAGE(26 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + 0),
	RGBA_IMAGE(27 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + 0),
	CIRCLES(28 * e_PLOT_STYLE_FLAGS.PLOT_STYLE_BITS + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_LINE + e_PLOT_STYLE_FLAGS.PLOT_STYLE_HAS_FILL);

	private int intValue;
	private static java.util.HashMap<Integer, PLOT_STYLE> mappings;
	private static java.util.HashMap<Integer, PLOT_STYLE> getMappings()
	{
		if (mappings == null)
		{
			synchronized (PLOT_STYLE.class)
			{
				if (mappings == null)
				{
					mappings = new java.util.HashMap<Integer, PLOT_STYLE>();
				}
			}
		}
		return mappings;
	}

	private PLOT_STYLE(int value)
	{
		intValue = value;
		PLOT_STYLE.getMappings().put(value, this);
	}

	public int getValue()
	{
		return intValue;
	}

	public static PLOT_STYLE forValue(int value)
	{
		return getMappings().get(value);
	}
}